# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
# Example configuration.yaml entry
zeroconf:
# Text to speech
tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    base_url: !secret url
    service_name: google_say

# group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
zone: !include zones.yaml
sensors: !include sensors.yaml
# spotify:
  #client_id: !secret spotify_client_id
  #client_secret: !secret spotify_client_secret
frontend:
  themes: !include_dir_merge_named themes

# GitHub Integration
sensor:
  - platform: github
    access_token: !secret github_access_token
    repositories:
      - path: "twhite96/SuburbanSmarts"
        name: SuburbanSmarts
      - path: "twhite96/js-dev-reads"
        name: JS Dev Reads
      - path: "twhite96/checkyoself"
        name: Check Yo Self
      - path: "twhite96/portfolio-v5"
        name: Portfolio

# Custom Themes Input Select
input_select:

## iFrames

#################################################################
#                                                               #
#                        SSL/Server Config                      #
#                                                               #
#################################################################



http:
  # server_port: 8123
  # ssl_certificate: /ssl/fullchain.pem
  # ssl_key: /ssl/privkey.pem

#################################################################
#                                                               #
#                        Groups                                 #
#                                                               #
#################################################################

group: !include_dir_merge_named groups
light: !include light_groups.yaml

device_tracker:
  - platform: iphonedetect
    consider_home: 60
    new_device_defaults:
      track_new_devices: true
    hosts:
      rick: 'ip-address'

# Example configuration.yaml entry
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  # "Project ID" in the Device Access Console (not Cloud Project ID!)
  project_id: !secret nest_project_id
  subscriber_id: !secret nest_subscriber_id