# nav:
#   - Home: index.md
#   - Getting Started: GettingStarted.md
#   - Hardware: Hardware/index.md
#   - Home Assistant:
#       - Screens: HomeAssistant/Screens/index.md
#       - Custom Components: HomeAssistant/Custom Components/index.md
#       - Lovelace: HomeAssistant/Lovelace/index.md
#       - Vacuum: HomeAssistant/Vacuum/index.md
#       - Voice Control: HomeAssistant/VoiceControl/index.md
#       - AppDaemon: HomeAssistant/AppDaemon/index.md
#       - Packages: HomeAssistant/Packages/index.md
#   - Software:
#       - Overview: Software/Overview.md
#       - Encryption: Software/Encryption.md
#       - Apps: Software/Apps.md
#       - Backup: Software/Backup.md
nav:
  - Home: index.md
  - Hardware: hardware.md
  - Software:
      - System Overview: Software/system-overview.md
      - Docker Containers: Software/docker.md
      - External Access: Software/external-access.md
      - Ad-Blocking: Software/ad-blocking.md
      - Ports: Software/ports.md
  - Home Assistant:
      - Introduction: HomeAssistant/introduction.md
      - Installed Addons: HomeAssistant/addons.md
      - Dashboards: HomeAssistant/dashboards.md
      - Custom Extensions: HomeAssistant/custom-extensions.md
      - Vacuum Setup: HomeAssistant/vacuum-setup.md
      - Speech: HomeAssistant/speech.md
      - Health Checks: HomeAssistant/health-checks.md
  - Topology: topology.md
  - Resources: resources.md
theme:
  # icon:
  #   admonition:
  #     note: fontawesome/solid/note-sticky
  #     abstract: fontawesome/solid/book
  #     info: fontawesome/solid/circle-info
  #     tip: fontawesome/solid/bullhorn
  #     success: fontawesome/solid/check
  #     question: fontawesome/solid/circle-question
  #     warning: fontawesome/solid/triangle-exclamation
  #     failure: fontawesome/solid/bomb
  #     danger: fontawesome/solid/skull
  #     bug: fontawesome/solid/robot
  #     example: fontawesome/solid/flask
  #     quote: fontawesome/solid/quote-left
  favicon: images/favi.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.tabs.sticky
    - toc.follow
    - search.highlight
    - search.share
    - search.suggest
  logo: "logo.svg"
  font:
    text: Fira Code
    code: Fira Code
  name: material
  custom_dir: overrides
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
repo_url: https://github.com/twhite96/SuburbanSmarts
repo_name: twhite96/SuburbanSmarts
extra:
  disqus: "SuburbanSmarts"
  social:
    - icon: "fontawesome/solid/globe"
      link: "https://suburbansmarts.org"
    - icon: "fontawesome/brands/github"
      link: "https://github.com/twhite96/SuburbanSmarts"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/SuburbanSmarts"
    - icon: "fontawesome/brands/youtube"
      link: "https://www.youtube.com/channel/UCANizz_NF-Xr6DrnSLg0Ogg"
copyright: "Copyright &copy; 2022 Tiffany White"
site_author: "Tiffany White"
site_name: Suburban Smarts
site_url: "https://docs.suburbansmarts.org/"
dev_addr: "0.0.0.0:8000"
site_description: "Documentation for my over-engineered smart apartment"
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: python/name:pymdownx.superfences.fence_code_format
