

# platform: netdata
# host: !secret docker_system
# port: '19999'
# name: NetData
# resources:
#   "NetData CPU":
#     data_group: 'cgroup_netdata.cpu_limit'
#     element: 'used'
#     icon: mdi:chip
#   "Plex CPU":
#     data_group: 'cgroup_plex-server.cpu_limit'
#     element: 'used'
#     icon: mdi:chip
#   "Sonarr CPU":
#     data_group: 'cgroup_sonarr.cpu_limit'
#     element: 'used'
#     icon: mdi:chip
#   "Radarr CPU":
#     data_group: 'cgroup_radarr.cpu_limit'
#     element: 'used'
#     icon: mdi:chip
#   "Bazarr CPU":
#     data_group: 'cgroup_bazarr.cpu_limit'
#     element: 'used'
#     icon: mdi:chip
#   "Lidarr CPU":
#     data_group: 'cgroup_lidarr.cpu_limit'
#     element: 'used'
#     icon: mdi:chip
#   "NextCloud CPU":
#     data_group: 'cgroup_nextcloud.cpu_limit'
#     element: 'used'
#     icon: mdi:chip
#   "Home Assistant CPU":
#     data_group: 'cgroup_nextcloud.cpu_limit'
#     element: 'used'
#     icon: mdi:chip
#   "Portainer CPU":
#     data_group: 'cgroup_portainer.cpu_limit'
#     element: 'used'
#     icon: mdi:chip
#   "Duplicati CPU":
#     data_group: 'cgroup_duplicati.cpu_limit'
#     element: 'used'
#     icon: mdi:chip
#   "MQTT CPU":
#     data_group: 'cgroup_mqtt.cpu_limit'
#     element: 'used'
#     icon: mdi:chip
#   "Ombi CPU":
#     data_group: 'cgroup_ombi.cpu_limit'
#     element: 'used'
#     icon: mdi:chip
#   "NodeRed CPU":
#     data_group: 'cgroup_node-red.cpu_limit'
#     element: 'used'
#     icon: mdi:chip
#   "Nzbget CPU":
#     data_group: 'cgroup_nzbget.cpu_limit'
#     element: 'used'
#     icon: mdi:chip
#   "MariaDB CPU":
#     data_group: 'cgroup_mariadb.cpu_limit'
#     element: 'used'
#     icon: mdi:chip
#   "Jackett CPU":
#     data_group: 'cgroup_jackett.cpu_limit'
#     element: 'used'
#     icon: mdi:chip
#   "Hydra2 CPU":
#     data_group: 'cgroup_hydra2.cpu_limit'
#     element: 'used'
#     icon: mdi:chip
#   "Bitwarden CPU":
#     data_group: 'cgroup_bitwarden.cpu_limit'
#     element: 'used'
#     icon: mdi:chip
#   "Transmission CPU":
#     data_group: 'cgroup_transmission.cpu_limit'
#     element: 'used'
#     icon: mdi:chip
#   "Guacamole CPU":
#     data_group: 'cgroup_guacamole.cpu_limit'
#     element: 'used'
#     icon: mdi:chip
#   "Tdarr CPU":
#     data_group: 'cgroup_tdarr.cpu_limit'
#     element: 'used'
#     icon: mdi:chip
#   "Unifi Controller CPU":
#     data_group: 'cgroup_unifi-controller.cpu_limit'
#     element: 'used'
#     icon: mdi:chip
#   "Watchtower CPU":
#     data_group: 'cgroup_watchtower.cpu_limit'
#     element: 'used'
#     icon: mdi:chip
#   "Traefik CPU":
#     data_group: 'cgroup_traefik.cpu_limit'
#     element: 'used'
#     icon: mdi:chip
#   "TasmoBackup CPU":
#     data_group: 'cgroup_tasmobackup.cpu_limit'
#     element: 'used'
#     icon: mdi:chip
#   "Organizr CPU":
#     data_group: 'cgroup_organizr.cpu_limit'
#     element: 'used'
#     icon: mdi:chip
#   "PHPMyAdmin CPU":
#     data_group: 'cgroup_phpmyadmin.cpu_limit'
#     element: 'used'
#     icon: mdi:chip
#   "VSCode CPU":
#     data_group: 'cgroup_code-server.cpu_limit'
#     element: 'used'
#     icon: mdi:chip